from pathlib import Path

path = Path('app/src/main/java/com/yamo/snorelab/LocationSharingActivity.java')
text = path.read_text(encoding='utf-8')

old = '''        LinearLayout bottom = new LinearLayout(this);\n        bottom.setPadding(dp(18), dp(10), dp(18), dp(10));\n        bottom.setBackgroundColor(BG);\n        actionButton = primaryButton(create ? "방 만들기" : "방 참여하기", create);\n        actionButton.setOnClickListener(v -> ensurePermissionsThenSubmit());\n        bottom.addView(actionButton, new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, dp(54)));\n        root.addView(bottom);\n'''
new = '''        LinearLayout bottom = new LinearLayout(this);\n        // Keep a little breathing room around the fixed CTA. The root already reserves\n        // the system navigation inset from the very first frame, so the button no longer\n        // appears clipped and then jumps upward a moment later.\n        bottom.setPadding(dp(18), dp(8), dp(18), dp(12));\n        bottom.setBackgroundColor(BG);\n        actionButton = primaryButton(create ? "방 만들기" : "방 참여하기", create);\n        actionButton.setOnClickListener(v -> ensurePermissionsThenSubmit());\n        bottom.addView(actionButton, new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, dp(52)));\n        root.addView(bottom);\n'''
if old not in text:
    raise SystemExit('showRoomForm bottom block not found')
text = text.replace(old, new, 1)

old = '''        LinearLayout panel = new LinearLayout(this);\n        panel.setOrientation(LinearLayout.VERTICAL);\n        panel.setPadding(dp(20), dp(20), dp(20), dp(18));\n        panel.setBackground(round(CARD, 26, 1, BORDER));\n\n        TextView title = text("내 상태 변경", 19, TEXT, true);\n'''
new = '''        LinearLayout panel = new LinearLayout(this);\n        panel.setOrientation(LinearLayout.VERTICAL);\n        panel.setPadding(dp(18), dp(18), dp(18), dp(16));\n        panel.setBackground(round(CARD, 24, 1, BORDER));\n\n        TextView title = text("내 상태 변경", 18, TEXT, true);\n'''
if old not in text:
    raise SystemExit('status picker panel block not found')
text = text.replace(old, new, 1)

old = '''        subtitle.setPadding(0, dp(5), 0, dp(14));\n'''
new = '''        subtitle.setPadding(0, dp(5), 0, dp(12));\n'''
if old not in text:
    raise SystemExit('status picker subtitle padding not found')
text = text.replace(old, new, 1)

old = '''        LinearLayout.LayoutParams cancelParams = new LinearLayout.LayoutParams(\n                ViewGroup.LayoutParams.MATCH_PARENT, dp(46));\n        cancelParams.topMargin = dp(14);\n'''
new = '''        LinearLayout.LayoutParams cancelParams = new LinearLayout.LayoutParams(\n                ViewGroup.LayoutParams.MATCH_PARENT, dp(44));\n        cancelParams.topMargin = dp(12);\n'''
if old not in text:
    raise SystemExit('status picker cancel block not found')
text = text.replace(old, new, 1)

old = '''            window.setLayout(Math.min(dp(360), screenWidth - dp(36)),\n                    ViewGroup.LayoutParams.WRAP_CONTENT);\n'''
new = '''            window.setLayout(Math.min(dp(356), screenWidth - dp(36)),\n                    ViewGroup.LayoutParams.WRAP_CONTENT);\n'''
if old not in text:
    raise SystemExit('status picker window width not found')
text = text.replace(old, new, 1)

old = '''    private void addStatusPickerRow(LinearLayout panel, Dialog dialog, String status, String label) {\n        boolean selected = status.equals(currentSelfStatus);\n        int statusColor = LocationStatusPalette.color(status);\n\n        LinearLayout row = new LinearLayout(this);\n        row.setOrientation(LinearLayout.HORIZONTAL);\n        row.setGravity(Gravity.CENTER_VERTICAL);\n        row.setPadding(dp(14), 0, dp(12), 0);\n        row.setBackground(round(LocationStatusPalette.softColor(status), 17, 1,\n                selected ? statusColor : BORDER));\n\n        View dot = new View(this);\n        dot.setBackground(statusDotDrawable(status, selected));\n        LinearLayout.LayoutParams dotParams = new LinearLayout.LayoutParams(\n                dp(selected ? 14 : 11), dp(selected ? 14 : 11));\n        dotParams.rightMargin = dp(10);\n        row.addView(dot, dotParams);\n\n        TextView name = text(label, 13, selected ? statusColor : TEXT, true);\n        name.setIncludeFontPadding(false);\n        row.addView(name, new LinearLayout.LayoutParams(0, dp(48), 1f));\n\n        TextView state = text(selected ? "현재 상태" : "변경", 10,\n                selected ? statusColor : MUTED, true);\n        state.setGravity(Gravity.END | Gravity.CENTER_VERTICAL);\n        state.setIncludeFontPadding(false);\n        row.addView(state, new LinearLayout.LayoutParams(dp(58), dp(48)));\n\n        if (selected) {\n            row.setEnabled(false);\n            row.setAlpha(0.56f);\n        } else {\n            row.setClickable(true);\n            row.setOnClickListener(v -> {\n                dialog.dismiss();\n                requestStatusChange(status);\n            });\n        }\n\n        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(\n                ViewGroup.LayoutParams.MATCH_PARENT, dp(50));\n        params.topMargin = dp(7);\n        panel.addView(row, params);\n    }\n'''
new = '''    private void addStatusPickerRow(LinearLayout panel, Dialog dialog, String status, String label) {\n        boolean selected = status.equals(currentSelfStatus);\n        int statusColor = LocationStatusPalette.color(status);\n\n        LinearLayout row = new LinearLayout(this);\n        row.setOrientation(LinearLayout.HORIZONTAL);\n        row.setGravity(Gravity.CENTER_VERTICAL);\n        row.setPadding(dp(13), 0, dp(10), 0);\n        row.setBackground(round(LocationStatusPalette.softColor(status), 16, 1,\n                selected ? statusColor : BORDER));\n\n        View dot = new View(this);\n        dot.setBackground(statusDotDrawable(status, selected));\n        LinearLayout.LayoutParams dotParams = new LinearLayout.LayoutParams(\n                dp(selected ? 12 : 10), dp(selected ? 12 : 10));\n        dotParams.rightMargin = dp(10);\n        row.addView(dot, dotParams);\n\n        TextView name = text(label, 13, selected ? statusColor : TEXT, true);\n        name.setGravity(Gravity.CENTER_VERTICAL);\n        name.setIncludeFontPadding(false);\n        row.addView(name, new LinearLayout.LayoutParams(\n                0, ViewGroup.LayoutParams.MATCH_PARENT, 1f));\n\n        TextView state = text(selected ? "현재 상태" : "변경", 10,\n                selected ? statusColor : MUTED, true);\n        state.setGravity(Gravity.CENTER);\n        state.setIncludeFontPadding(false);\n        state.setBackground(round(CARD, 13, 1, selected ? statusColor : BORDER));\n        row.addView(state, new LinearLayout.LayoutParams(dp(66), dp(30)));\n\n        // Keep the current state fully legible; disable only its click action.\n        // Fading the whole row made the selected state look visually broken.\n        row.setAlpha(1f);\n        if (selected) {\n            row.setClickable(false);\n            row.setFocusable(false);\n        } else {\n            row.setClickable(true);\n            row.setFocusable(true);\n            row.setOnClickListener(v -> {\n                dialog.dismiss();\n                requestStatusChange(status);\n            });\n        }\n\n        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(\n                ViewGroup.LayoutParams.MATCH_PARENT, dp(48));\n        params.topMargin = dp(6);\n        panel.addView(row, params);\n    }\n'''
if old not in text:
    raise SystemExit('addStatusPickerRow block not found')
text = text.replace(old, new, 1)

old = '''    private LinearLayout rootShell() {\n        LinearLayout root = new LinearLayout(this);\n        root.setOrientation(LinearLayout.VERTICAL);\n        root.setBackgroundColor(BG);\n        root.setPadding(0, dp(8), 0, dp(8));\n        if (Build.VERSION.SDK_INT >= 21) {\n            root.setOnApplyWindowInsetsListener((v, insets) -> {\n                int top;\n                int bottom;\n                if (Build.VERSION.SDK_INT >= 30) {\n                    top = insets.getInsets(WindowInsets.Type.statusBars()).top;\n                    bottom = insets.getInsets(WindowInsets.Type.navigationBars()).bottom;\n                } else {\n                    top = insets.getSystemWindowInsetTop();\n                    bottom = insets.getSystemWindowInsetBottom();\n                }\n                v.setPadding(0, top + dp(4), 0, bottom + dp(4));\n                return insets;\n            });\n            root.requestApplyInsets();\n        }\n        return root;\n    }\n'''
new = '''    private LinearLayout rootShell() {\n        LinearLayout root = new LinearLayout(this);\n        root.setOrientation(LinearLayout.VERTICAL);\n        root.setBackgroundColor(BG);\n\n        // Reserve system-bar space synchronously before the first frame. Previously the\n        // root started with only 8dp bottom padding and waited for onApplyWindowInsets,\n        // which made the fixed bottom CTA appear clipped and then jump upward later.\n        final int initialTop = initialStatusBarInset();\n        final int initialBottom = initialNavigationBarInset();\n        root.setPadding(0, initialTop + dp(4), 0, initialBottom + dp(6));\n\n        if (Build.VERSION.SDK_INT >= 21) {\n            root.setOnApplyWindowInsetsListener((v, insets) -> {\n                int top;\n                int bottom;\n                if (Build.VERSION.SDK_INT >= 30) {\n                    top = insets.getInsets(WindowInsets.Type.statusBars()).top;\n                    bottom = insets.getInsets(WindowInsets.Type.navigationBars()).bottom;\n                } else {\n                    top = insets.getSystemWindowInsetTop();\n                    bottom = insets.getSystemWindowInsetBottom();\n                }\n                top = Math.max(top, initialTop);\n                bottom = Math.max(bottom, initialBottom);\n                v.setPadding(0, top + dp(4), 0, bottom + dp(6));\n                return insets;\n            });\n            root.post(root::requestApplyInsets);\n        }\n        return root;\n    }\n\n    private int initialStatusBarInset() {\n        if (Build.VERSION.SDK_INT >= 30) {\n            try {\n                return getWindowManager().getCurrentWindowMetrics().getWindowInsets()\n                        .getInsetsIgnoringVisibility(WindowInsets.Type.statusBars()).top;\n            } catch (Exception ignored) { }\n        }\n        return systemDimensionPx("status_bar_height");\n    }\n\n    private int initialNavigationBarInset() {\n        if (Build.VERSION.SDK_INT >= 30) {\n            try {\n                return getWindowManager().getCurrentWindowMetrics().getWindowInsets()\n                        .getInsetsIgnoringVisibility(WindowInsets.Type.navigationBars()).bottom;\n            } catch (Exception ignored) { }\n        }\n        return systemDimensionPx("navigation_bar_height");\n    }\n\n    private int systemDimensionPx(String name) {\n        int id = getResources().getIdentifier(name, "dimen", "android");\n        return id == 0 ? 0 : getResources().getDimensionPixelSize(id);\n    }\n'''
if old not in text:
    raise SystemExit('rootShell block not found')
text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
print('patched LocationSharingActivity visual polish')
