from pathlib import Path

path = Path('app/src/main/java/com/yamo/snorelab/LocationSharingActivity.java')
text = path.read_text(encoding='utf-8')

old = '''        LinearLayout roomRow = new LinearLayout(this);\n        roomRow.setOrientation(LinearLayout.HORIZONTAL);\n        roomRow.setGravity(Gravity.CENTER_VERTICAL);\n        roomNameInput = input(create ? "예) 야모네 스키 여행" : "참여할 방 이름을 입력하세요",\n                InputType.TYPE_CLASS_TEXT);\n        roomNameInput.setSingleLine(true);\n        roomNameInput.setFilters(new InputFilter[]{new InputFilter.LengthFilter(40)});\n        roomRow.addView(roomNameInput, new LinearLayout.LayoutParams(0, dp(52), 1f));\n\n        availabilityButton = smallButton("중복 확인");\n        availabilityButton.setTextSize(13);\n        availabilityButton.setGravity(Gravity.CENTER);\n        availabilityButton.setIncludeFontPadding(false);\n        LinearLayout.LayoutParams checkParams = new LinearLayout.LayoutParams(dp(96), dp(46));\n        checkParams.leftMargin = dp(8);\n        if (create) roomRow.addView(availabilityButton, checkParams);\n'''
new = '''        LinearLayout roomRow = new LinearLayout(this);\n        roomRow.setOrientation(LinearLayout.HORIZONTAL);\n        roomRow.setGravity(Gravity.CENTER_VERTICAL);\n        // EditText and Button both expose a text baseline. Disable LinearLayout's\n        // baseline alignment so the smaller action button is positioned by its box,\n        // not pulled upward to match the EditText text baseline.\n        roomRow.setBaselineAligned(false);\n        roomNameInput = input(create ? "예) 야모네 스키 여행" : "참여할 방 이름을 입력하세요",\n                InputType.TYPE_CLASS_TEXT);\n        roomNameInput.setSingleLine(true);\n        roomNameInput.setFilters(new InputFilter[]{new InputFilter.LengthFilter(40)});\n        roomRow.addView(roomNameInput, new LinearLayout.LayoutParams(0, dp(52), 1f));\n\n        availabilityButton = smallButton("중복 확인");\n        availabilityButton.setTextSize(14);\n        availabilityButton.setGravity(Gravity.CENTER);\n        availabilityButton.setIncludeFontPadding(false);\n        availabilityButton.setPadding(0, 0, 0, 0);\n\n        // Give the button the same 52dp layout slot as the input, then center a\n        // slightly smaller 48dp button inside it. This makes vertical alignment\n        // deterministic across fonts, keyboards and Android button implementations.\n        LinearLayout availabilitySlot = new LinearLayout(this);\n        availabilitySlot.setGravity(Gravity.CENTER);\n        availabilitySlot.addView(availabilityButton, new LinearLayout.LayoutParams(\n                ViewGroup.LayoutParams.MATCH_PARENT, dp(48)));\n        LinearLayout.LayoutParams checkParams = new LinearLayout.LayoutParams(dp(96), dp(52));\n        checkParams.leftMargin = dp(8);\n        if (create) roomRow.addView(availabilitySlot, checkParams);\n'''
if old not in text:
    raise SystemExit('duplicate check row block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('patched duplicate check slot alignment')
